version: 2

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

python:
  version: 3.7
  install:
    - requirements: docs/requirements_1.txt
    - requirements: docs/requirements_new.txt